### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by Error-Cezar** [jferard/py4lo#36]
py4lo doesn't seem to have any documentation.
Would it be possible to have one for easier use of the modules?

**Comment by jferard** [comment]
Hi, sorry for the late answer.

There are two main parts in Py4LO: 

* the tool that wraps your code into an ODS document
* the library

I don't  have the time to write a comprehensive documentation.

Concerning the tool, you have an introduction in the README and a few examples that should be sufficient to start. There is really no more that what you'll find in the examples : create a TOML file, add a few directives and run the command line to create and open the document in LibreOffice.

But I agree that the library should have complete docstrings, with examples. I will try to improve this.

**Comment by jferard** [comment]
Is something like that : https://github.com/jferard/py4lo/commit/a7a0c08a891a3e9950baaaf00644c7a757c1a982 what you expect?

**Comment by jferard** [comment]
https://github.com/jferard/py4lo/commit/3d19d290d2751f7ae0c274255d4f2bfd4b0848bc

**Comment by Error-Cezar** [comment]
Yup, works that way
Thanks!

**Comment by jferard** [comment]
https://github.com/jferard/py4lo/commit/c59424b97af4ca3d7ecad2a00d3a53f8f414c152

**Comment by jferard** [comment]
https://github.com/jferard/py4lo/commit/9256f79a132749487e263e504c45045609d57e7a

**Comment by jferard** [comment]
https://github.com/jferard/py4lo/commit/f4fadea83d2aeb6fed6c204512a951f19d6998e1

**Comment by jferard** [comment]
https://github.com/jferard/py4lo/commit/1c4d7553f0b7093f2bac3ff91fece181858d8e36 and https://github.com/jferard/py4lo/commit/18c015931515e2c6a4e6e33328d1cfbce79a1a08 to close the issue. Hope it helps!
